# YAML doc:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

resources:
- repo: self

# Stages:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#stage
stages:
- stage:  deploy_kusto
  displayName:  Deploy Kusto end-2-end
  # Variables:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#variables
  variables: []
  # Those variables should be defined in the UI as they are specific to a given environment (e.g. cluster name)
  #   clusterName:  Name of Azure Data Explorer cluster
  #   serviceConnection:  Name of Azure DevOps connection used to ARM-deploy
  #   appId:  Client ID of the service principal used to interact with the cluster
  #   appSecret:  Secret of the service principal
  jobs:
  - job:  e2e_deploy
    pool:
      vmImage: 'ubuntu-latest'
    variables:  []
    steps:
    # Infrastructure
    # ARM Template:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
    - task: AzureResourceManagerTemplateDeployment@3
      displayName:  Infrastructure
      inputs:
        deploymentScope: 'Resource Group'
        # Here we don't specify the subscriptionId nor resourceGroupName
        # because they are already specified in our service connection
        azureResourceManagerConnection: $(serviceConnection)
        action: 'Create Or Update Resource Group'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: kusto-infra.json
        overrideParameters:  "-clusterName $(CLUSTERNAME)"
        deploymentMode: 'Incremental'
    # Schema Entities
    # To install the Azure Data Explorer - Pipeline tool extension, see https://docs.microsoft.com/en-us/azure/data-explorer/devops
    - task: Azure-Kusto.PublishToADX.PublishToADX.PublishToADX@1
      displayName:  Schema Entities
      inputs:
        files: 'MyDatabase.kql'
        parallelCommands: false
        kustoUrls: "https://$(CLUSTERNAME).kusto.windows.net:443?DatabaseName=myDatabase"
        customAuth: false
        aadClientId: $(APPID)
        aadClientSecret: $(APPSECRET)
