# YAML doc:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

resources:
- repo: self

# Stages:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#stage
stages:
- stage:  deploy_kusto
  displayName:  Deploy Kusto end-2-end
  # Variables:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#variables
  variables: []
  # Those variables should be defined in the UI as they are specific to a given environment (e.g. cluster name)
  #   clusterName:  Name of Azure Data Explorer cluster
  #   serviceConnection:  Name of Azure DevOps connection used to ARM-deploy
  #   appId:  Client ID of the service principal used to interact with the cluster
  #   appSecret:  Secret of the service principal
  #   appTenantId:  Tenant ID of the service principal
  #   location:  Azure region, e.g. eastus
  jobs:
  - job:  e2e_deploy
    pool:
      vmImage: windows-latest
    variables:  []
    steps:
    # Download Microsoft.Azure.Kusto.Tools
    - bash:  |
        # Download from nuget.org
        nuget install Microsoft.Azure.Kusto.Tools
        # Rename the folder (including the most recent version)
        mv Microsoft.Azure.Kusto.Tools.* kusto.tools
      displayName:  Download Kusto.Tools Nuget package
    # Ingest Data
    # Run LightIngest
    - bash:  |
        # Define the connection string to the cluster's database, including service principal's credentials
        connectionString="https://ingest-$(CLUSTERNAME).$(location).kusto.windows.net/myDatabase;Fed=true;AppClientId=$(appId);AppKey=$(appSecret);TenantId=$(appTenantId)"
        echo "connectionString:  $connectionString"
        # Define absolute path for CSV file
        filePath="$(pwd)/customers.csv"
        echo "filePath:  $filePath"
        # Execute a KQL script against the database
        kusto.tools/tools/LightIngest $connectionString -db:myDatabase -table:Customer -sourcePath:"$filePath" -format:csv -ignoreFirst:true
      displayName:  Ingest Data
    # Schema Entities
    # Run Kusto.CLI
    - bash:  |
        # Define the connection string to the cluster's database, including service principal's credentials
        connectionString="https://$(CLUSTERNAME).$(location).kusto.windows.net/myDatabase;Fed=true;AppClientId=$(appId);AppKey=$(appSecret);TenantId=$(appTenantId)"
        echo "connectionString:  $connectionString"
        # Execute a KQL script against the database
        kusto.tools/tools/Kusto.Cli $connectionString -script:MyDatabase.kql
      displayName:  Schema Entities
    # Infrastructure
    # ARM Template:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
    - task: AzureResourceManagerTemplateDeployment@3
      displayName:  Infrastructure
      inputs:
        deploymentScope: 'Resource Group'
        # Here we don't specify the subscriptionId nor resourceGroupName
        # because they are already specified in our service connection
        azureResourceManagerConnection: $(serviceConnection)
        action: 'Create Or Update Resource Group'
        location: $(location)
        templateLocation: 'Linked artifact'
        csmFile: kusto-infra.json
        overrideParameters:  "-clusterName $(CLUSTERNAME)"
        deploymentMode: 'Incremental'
