# YAML doc:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema

resources:
- repo: self

# Stages:  https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema#stage
stages:
- stage:  deploy_kusto
  displayName:  Deploy Kusto end-2-end
  variables:  []
  jobs:
  - job:  e2e_deploy
    pool:
      vmImage: 'ubuntu-latest'
    variables:  []
    steps:
    # ARM Template:  https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-resource-group-deployment
    - task: AzureResourceManagerTemplateDeployment@3
      displayName:  ARM Template deployment
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: 'vp-auto-kusto-article'
        # subscriptionId: '69a0e064-0dce-4437-96ef-7105728ff58e'
        # resourceGroupName: 'vp-article'
        action: 'Create Or Update Resource Group'
        location: 'East US'
        templateLocation: 'Linked artifact'
        csmFile: kusto-infra.json
        overrideParameters:  "-clusterName $(CLUSTERNAME)"
        deploymentMode: 'Incremental'
    # To install the Azure Data Explorer - Pipeline tool extension, see https://docs.microsoft.com/en-us/azure/data-explorer/devops
    - task: PublishToADX@1
      inputs:
        files: 'MyDatabase.kql'
        parallelCommands: false
        kustoUrls: 'https://$(CLUSTERNAME).kusto.windows.net:443?DatabaseName=myDatabase'
        customAuth: false
        aadClientId: 'myid'
        aadClientSecret: 'my-secret'